# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fancystruct}
  s.version = "0.9.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Myles Byrne"]
  s.date = %q{2009-11-10}
  s.email = %q{myles@myles.id.au}
  s.files = [
    ".gitignore",
     "Rakefile",
     "VERSION",
     "examples.rb",
     "fancystruct.gemspec",
     "lib/fancystruct.rb"
  ]
  s.homepage = %q{http://github.com/quackingduck/fancystruct}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Like Struct, but fancy}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<exemplor>, [">= 2000.0.0"])
    else
      s.add_dependency(%q<exemplor>, [">= 2000.0.0"])
    end
  else
    s.add_dependency(%q<exemplor>, [">= 2000.0.0"])
  end
end
